#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get -y install haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 49666-web-01 100.26.227.216:80 check
   server 49666-web-02 3.84.239.219:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
