#!/usr/bin/env bash
#Displays Best School 10 times, but for the 9th iteration,
#	displays Best School and then Hi on a new line.

i=0

while [[ $i -lt 10 ]]
do
	if [[ $i == 3 ]]; then
		echo "bad luck"
	elif [[ $i == 7 ]]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	(( i++ ))
done
