#!/usr/bin/env bash
#displays the content of the current directory in a list format
#where only the part of the name after the first dash is displayed

ls=$(ls)

for i in $ls; do
	echo "$i" | cut -d "-" -f2
done
